from django.urls import path
from frontend import views

urlpatterns = [
    path("userlogin", views.userlogin, name="userlogin"),
    path("usave", views.usave, name="usave"),
    path("ulogin", views.ulogin, name="ulogin"),
    path("ulogout", views.ulogout, name="ulogout"),
    path("index/", views.index, name="index"),
    path("addfriend/<str:name>", views.addfriend, name="addfriend"),
    path("chat/<str:username>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),

    path("", views.homepage, name="homepage"),
    path("post/", views.post, name="post"),
    path("products/", views.products, name="products"),
    path('userlogin/', views.userlogin, name="userlogin"),
    path('usave/', views.usave, name="usave"),
    path('ulogin/', views.ulogin, name="ulogin"),
    path('ulogout/', views.ulogout, name="ulogout"),
    path('myads/', views.myads, name="myads"),
    path('allp/', views.allp, name="allp"),
    path('editprod/<int:pid>/', views.editprod, name="editprod"),
    path('epsave/<int:pid>/', views.epsave, name="epsave"),
    path('pdetails/<int:pid>/', views.pdetails, name="pdetails"),
    path('editprofile/', views.editprofile, name="editprofile"),
    path('passchange/', views.passchange, name="passchange"),
    path('updateprof/<int:uid>/', views.updateprof, name="updateprof"),
    path('pasupd/<int:uid>/', views.pasupd, name="pasupd"),
    path('myproduct/<int:pid>/', views.myproduct, name="myproduct"),
    path('pdel/<int:pid>/', views.pdel, name="pdel"),
    path('contact/', views.contact, name="contact"),
    path('csave/', views.csave, name="csave"),
    path('about/', views.about, name="about"),
    path('catfilter/<cn>/', views.catfilter, name="catfilter"),
    path('priv/', views.priv, name="priv"),
    path('deleteacc/', views.deleteacc, name="deleteacc"),
    path('cityallp/<dis>/', views.cityallp, name="cityallp"),
    path('searchpro/', views.searchpro, name="searchpro"),
    path('searchproducts/', views.searchproducts, name="searchproducts"),
    path('userp/<un>/', views.userp, name="userp"),
    path('addwishlist/<int:id>/', views.addwishlist, name="addwishlist"),
    path('favads/', views.favads, name="favads"),
    path('deletewish/<int:itemid>/', views.deletewish, name="deletewish"),
]
